services:
  db:
    image: postgres:17.4-alpine
    container_name: findly-db-prod
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATABASE: findly
      POSTGRES_DB: findly
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    volumes:
      - findly-db-data:/var/lib/postgresql/data

  app:
    container_name: findly-migrate
    build:
      context: .
      dockerfile: docker/Dockerfile.migrations
    depends_on:
      - db
    volumes:
      - /app/node_modules
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/findly?schema=public

networks:
  app-network:
    driver: bridge

volumes:
  findly-db-data:
    driver: local
