# Install dependencies only when needed
FROM node:24-alpine AS deps

WORKDIR /app
RUN npm install drizzle-orm pg dotenv drizzle-kit
COPY . .
CMD ["node", "--experimental-strip-types", "src/db/migrate.ts"]